### ISSUE TITLE
file-location-0.4.7 can't compile its test suite

### ISSUE THREAD

**Issue by peti** [gregwebs/FileLocation.hs#13]
Citing from http://hydra.cryp.to/build/538169/log/raw:

    Preprocessing test suite 'test' for file-location-0.4.7...

    Debug/FileLocation.hs:11:8:
        Could not find module ‘Language.Haskell.TH.Instances’
        It is a member of the hidden package ‘th-orphans-0.9.0’.
        Perhaps you need to add ‘th-orphans’ to the build-depends in your .cabal file.

**Comment by gregwebs** [comment]
Thanks! This is fixed in 0.4.7.1
